# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recordio.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


# fmt: off
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0erecordio.proto\x12\x08mxnet.io"T\n\nRecordUnit\x12"\n\x04head\x18\x01 \x01(\x0b\x32\x14.mxnet.io.RecordHead\x12"\n\x04\x62ody\x18\x02 \x01(\x0b\x32\x14.mxnet.io.RecordBody":\n\nRecordHead\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0f\n\x07reserve\x18\x02 \x01(\x04\x12\x0f\n\x07version\x18\x03 \x01(\x02"c\n\nRecordBody\x12"\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x14.mxnet.io.RecordData\x12\r\n\x05label\x18\x02 \x03(\x02\x12"\n\x05\x65xtra\x18\x03 \x03(\x0b\x32\x13.mxnet.io.ExtraData"5\n\nRecordData\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\r\n\x05value\x18\x03 \x01(\x0c"5\n\tExtraData\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\r\n\x05value\x18\x03 \x01(\x0c'  # noqa
)
# fmt: off


_RECORDUNIT = DESCRIPTOR.message_types_by_name["RecordUnit"]
_RECORDHEAD = DESCRIPTOR.message_types_by_name["RecordHead"]
_RECORDBODY = DESCRIPTOR.message_types_by_name["RecordBody"]
_RECORDDATA = DESCRIPTOR.message_types_by_name["RecordData"]
_EXTRADATA = DESCRIPTOR.message_types_by_name["ExtraData"]
RecordUnit = _reflection.GeneratedProtocolMessageType(
    "RecordUnit",
    (_message.Message,),
    {
        "DESCRIPTOR": _RECORDUNIT,
        "__module__": "recordio_pb2"
        # @@protoc_insertion_point(class_scope:mxnet.io.RecordUnit)
    },
)
_sym_db.RegisterMessage(RecordUnit)

RecordHead = _reflection.GeneratedProtocolMessageType(
    "RecordHead",
    (_message.Message,),
    {
        "DESCRIPTOR": _RECORDHEAD,
        "__module__": "recordio_pb2"
        # @@protoc_insertion_point(class_scope:mxnet.io.RecordHead)
    },
)
_sym_db.RegisterMessage(RecordHead)

RecordBody = _reflection.GeneratedProtocolMessageType(
    "RecordBody",
    (_message.Message,),
    {
        "DESCRIPTOR": _RECORDBODY,
        "__module__": "recordio_pb2"
        # @@protoc_insertion_point(class_scope:mxnet.io.RecordBody)
    },
)
_sym_db.RegisterMessage(RecordBody)

RecordData = _reflection.GeneratedProtocolMessageType(
    "RecordData",
    (_message.Message,),
    {
        "DESCRIPTOR": _RECORDDATA,
        "__module__": "recordio_pb2"
        # @@protoc_insertion_point(class_scope:mxnet.io.RecordData)
    },
)
_sym_db.RegisterMessage(RecordData)

ExtraData = _reflection.GeneratedProtocolMessageType(
    "ExtraData",
    (_message.Message,),
    {
        "DESCRIPTOR": _EXTRADATA,
        "__module__": "recordio_pb2"
        # @@protoc_insertion_point(class_scope:mxnet.io.ExtraData)
    },
)
_sym_db.RegisterMessage(ExtraData)

if _descriptor._USE_C_DESCRIPTORS is False:

    DESCRIPTOR._options = None
    _RECORDUNIT._serialized_start = 28
    _RECORDUNIT._serialized_end = 112
    _RECORDHEAD._serialized_start = 114
    _RECORDHEAD._serialized_end = 172
    _RECORDBODY._serialized_start = 174
    _RECORDBODY._serialized_end = 273
    _RECORDDATA._serialized_start = 275
    _RECORDDATA._serialized_end = 328
    _EXTRADATA._serialized_start = 330
    _EXTRADATA._serialized_end = 383
# @@protoc_insertion_point(module_scope)
