/// \file
/// \ref CurrentVersion Module
///
/// This file is intentional not included by `hbrt4-c.h`
/// So it is easier for users to to handle cache hit rate of
/// compiler caching tool, such as `ccache`
///
/// This file is automatically generated
///
/// \author Horizon Robotics, Inc
/// \copyright All rights reserved
/// \since \CURRENT_HBRT4_VERSION

#pragma once

/// \ingroup Version
/// \defgroup CurrentVersion Current Version
/// Static HBRT version constants for current HBRT4 Version
///
/// @{

// clang-format off

/// Major version of HBRT4 toolkit of HBRT4 header file
/// \since \CURRENT_HBRT4_VERSION
static const int HBRT4_TOOLKIT_VERSION_MAJOR = 4;

/// Minor version of HBRT4 toolkit of HBRT4 header file
/// \since \CURRENT_HBRT4_VERSION
static const int HBRT4_TOOLKIT_VERSION_MINOR = 1;

/// Patch version of HBRT4 toolkit of HBRT4 header file
/// \since \CURRENT_HBRT4_VERSION
static const int HBRT4_TOOLKIT_VERSION_PATCH = 17;

// clang-format on

/// Pre version of HBRT4 toolkit of HBRT4 header file. May be empty
/// \since \CURRENT_HBRT4_VERSION
static const char *HBRT4_TOOLKIT_VERSION_PRE_RELEASE = "";

/// Extra version of HBRT4 toolkit of HBRT4 header file. May be empty
/// \since \CURRENT_HBRT4_VERSION
static const char *HBRT4_TOOLKIT_VERSION_EXTRA = "";

/// Git commit hash of HBRT4 toolkit of HBRT4 header file
/// \since \CURRENT_HBRT4_VERSION
static const char *HBRT4_TOOLKIT_VERSION_COMMIT_HASH = "077bbeac2c9b571d6851b7bbcc43590ffd947413";

/// Full string representation of HBRT4 toolkit version of HBRT4 header file
/// \since \CURRENT_HBRT4_VERSION
static const char *HBRT4_TOOLKIT_VERSION = "4.1.17";

/// @}
